# Kalman VAE
- Original paper: A Disentangled Recognition and Nonlinear DynamicsModel for Unsupervised Learning (https://arxiv.org/pdf/1710.05741.pdf)
- Original code: https://github.com/simonkamronn/kvae

## Kalman VAE summary
>KVAE disentangles two latent representations: an object’s representation, coming from a recognition model, and a latent state describing its dynamics. As a result, the evolution of the world can be imagined and missing data imputed, both without the need to generate high dimensional frames at each time step.

In [1]:
from tqdm import tqdm

import torch
from torch import optim
import torch.nn as nn
import torch.nn.functional as F
from torchvision import transforms, datasets
from tensorboardX import SummaryWriter

from pixyz.utils import print_latex

In [2]:
batch_size = 128
epochs = 1
seed = 1
torch.manual_seed(seed)

In [3]:
if torch.cuda.is_available():
    device = "cuda"
else:
    device = "cpu"

In [4]:
# generate MNIST by stacking row images(consider row as time step)
def init_dataset(f_batch_size):
    kwargs = {'num_workers': 1, 'pin_memory': True}
    data_dir = '../data'
    mnist_transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Lambda(lambda data: data[0])
    ])
    train_loader = torch.utils.data.DataLoader(
        datasets.MNIST(data_dir, train=True, download=True,
                       transform=mnist_transform),
        batch_size=f_batch_size, shuffle=True, **kwargs)
    test_loader = torch.utils.data.DataLoader(
        datasets.MNIST(data_dir, train=False, transform=mnist_transform),
        batch_size=f_batch_size, shuffle=True, **kwargs)

    fixed_t_size = 28
    return train_loader, test_loader, fixed_t_size

train_loader, test_loader, t_max = init_dataset(batch_size)

## Define probability distributions
### In the original paper
Prior: $p_{\gamma}({\bf a}|{\bf u}) = {\int p_{\gamma}({\bf a}|{\bf z})p_{\gamma}({\bf z}|{\bf u})d{\bf z}}$ (equation (3) in the paper)

Generator: $p_{\theta}({\bf x}|{\bf a}) = \prod_{t=1}^{T}p_{\theta}(x_t | a_t)$  
>$p_{\theta}(x_t|a_t)$ is a deep neural network parameterized by θ, that emits either a factorized Gaussian or Bernoulli probability vector depending on the data type of $x_t$.

Inference:  $q_{\phi}({\bf a}|{\bf x}) = \prod_{t=1}^{T}q_{\phi}(a_t | x_t)$  
$q_{\phi}(a_t | x_t) = {\cal N}(\mu_{\phi}(x_t), \Sigma_{\phi}(x_t))$
>$q_{\phi}(a_t|x_t)$ is a deep neural network that maps xt to the mean and the diagonal covariance of a Gaussian distribution.  

LGSSM:  
$p_{\gamma_{t}}\left(\mathbf{z}_{t} | \mathbf{z}_{t-1}, \mathbf{u}_{t}\right)=\mathcal{N}\left(\mathbf{z}_{t} ; \mathbf{A}_{t} \mathbf{z}_{t-1}+\mathbf{B}_{t} \mathbf{u}_{t}, \mathbf{Q}\right), \quad p_{\gamma_{t}}\left(\mathbf{a}_{t} | \mathbf{z}_{t}\right)=\mathcal{N}\left(\mathbf{a}_{t} ; \mathbf{C}_{t} \mathbf{z}_{t}, \mathbf{R}\right)$ (equation (1) in the paper)

$p_{\gamma}(\mathbf{a}, \mathbf{z} | \mathbf{u})=\prod_{t=1}^{T} p_{\gamma_{t}}\left(\mathbf{a}_{0: t-1}\right)\left(\mathbf{a}_{t} | \mathbf{z}_{t}\right) \cdot p\left(\mathbf{z}_{1}\right) \prod_{t=2}^{T} p_{\gamma_{t}\left(\mathbf{a}_{0: t-1}\right)}\left(\mathbf{z}_{t} | \mathbf{z}_{t-1}, \mathbf{u}_{t}\right)$ (equation (8) in the paper)

dynamics parameter network: 
${\bf \alpha}_t = {\bf \alpha}_t(a_{0:t-1})$  
${\bf d}_t = LSTM(a_{t-1}, d_{t-1})$  
${\bf \alpha}_t = softmax({\bf d}_t)$
$\mathbf{A}_{t}=\sum_{k=1}^{K} \alpha_{t}^{(k)}\left(\mathbf{a}_{0: t-1}\right) \mathbf{A}^{(k)}, \quad \mathbf{B}_{t}=\sum_{k=1}^{K} \alpha_{t}^{(k)}\left(\mathbf{a}_{0: t-1}\right) \mathbf{B}^{(k)}, \quad \mathbf{C}_{t}=\sum_{k=1}^{K} \alpha_{t}^{(k)}\left(\mathbf{a}_{0: t-1}\right) \mathbf{C}^{(k)}$

## 実装するやつ
Prior: 
$p_{\gamma}(a_{t\_pred} | C_t, z_{mu\_t\_pred}, R)$

Generator: 
$p_{\theta}(x_t | a_t)$

Inference: 
$q_{\phi}(a_t | x_t)$

Dynamics parameter network ($LSTM(d_t |a_{t-1}, d_{t-1})$含む):  
$p_{\gamma}(A_t, B_t, C_t | a_{0:t-1})$

z_prediction(Transition):  
$p_{\gamma}(z_{mu\_t\_pred}, z_{sigma\_t\_pred} | At, Bt, u_t, z_{mu\_prev}, z_{sigma\_prev})$

filter:
$p_{\gamma}(z_{mu\_t}, z_{sigma\_t} | C_t, a_{t\_pred}, a_t, z_{mu\_t\_pred}, z_{sigma\_t\_pred})$

smooth:
確認中

In [5]:
# https://github.com/simonkamronn/kvae/blob/849d631dbf2faf2c293d56a0d7a2e8564e294a51/kvae/KalmanVariationalAutoencoder.py#L97

from pixyz.distributions import Normal
class Inference(Normal):
    def __init__(self, x_dim, a_dim):
        super(Inference, self).__init__(name="q_phi", cond_var=["x_t"], var=["a_t"])
        self.fc1 = nn.Linear(x_dim, 25)
        self.fc2 = nn.Linear(25, 25)
        
        self.fc3_1 = nn.Linear(25, a_dim)
        self.fc3_2 = nn.Linear(25, a_dim)
    
    def forward(self, x):
        h = F.relu(self.fc1(x))
        h = F.relu(self.fc2(h))
        return {"loc": self.fc3_1(h), "scale": F.softplus(self.fc3_2(h))}

In [6]:
encoder = Inference(44, 44)
print_latex(encoder)

<IPython.core.display.Math object>

In [7]:
# https://github.com/simonkamronn/kvae/blob/849d631dbf2faf2c293d56a0d7a2e8564e294a51/kvae/KalmanVariationalAutoencoder.py#L132

from pixyz.distributions import Bernoulli
class Generator(Bernoulli):
    def __init__(self, a_dim, x_dim):
        super(Generator, self).__init__(name="p_theta", cond_var=["a_t"], var=["x_t"])
        self.fc1 = nn.Linear(a_dim, 25)
        self.fc2 = nn.Linear(25, 25)
        
        self.fc3 = nn.Linear(25, x_dim)
    
    def forward(self, a):
        h = F.relu(self.fc1(a))
        h = F.relu(self.fc2(h))
        return {"probs": torch.sigmoid(self.fc3(h))}

In [8]:
g = Generator(44, 44)
print_latex(g)

<IPython.core.display.Math object>

In [9]:
# https://github.com/simonkamronn/kvae/blob/849d631dbf2faf2c293d56a0d7a2e8564e294a51/kvae/KalmanVariationalAutoencoder.py#L176

from pixyz.distributions import Deterministic
class RNN(Deterministic):
    def __init__(self, a_dim, d_dim):
        super(RNN, self).__init__(name="LSTM", cond_var=["a_prev", "d_prev"], var=["d"])
        # d_dim = 50
        self.rnn = nn.LSTMCell(a_dim, d_dim)
        
    def forward(self, a_prev, d_prev):
        h, _ = self.rnn(a_prev, d_prev)
        return {"d": h}

In [10]:
# https://github.com/simonkamronn/kvae/blob/849d631dbf2faf2c293d56a0d7a2e8564e294a51/kvae/KalmanVariationalAutoencoder.py#L220

from pixyz.distributions import Deterministic

In [11]:
r = RNN(10, 50)
print_latex(r)

<IPython.core.display.Math object>

In [12]:
# https://github.com/simonkamronn/kvae/blob/849d631dbf2faf2c293d56a0d7a2e8564e294a51/kvae/KalmanVariationalAutoencoder.py#L220

from pixyz.distributions import Deterministic
class DynamicParameterNetwork(Deterministic):
    def __init__(self, d_dim, k_num):
        super(DynamicParameterNetwork, self).__init__(name="p_alpha", cond_var=["d"], var=["alpha"])
        self.fc1 = nn.Linear(d_dim, k_num)
        
    def forward(self, d):
        return {"alpha": F.softmax(self.fc1(d))}

In [13]:
a = DynamicParameterNetwork(50, 3)
print_latex(a)

<IPython.core.display.Math object>

In [14]:
Dynamic = a * r
print_latex(Dynamic)

<IPython.core.display.Math object>

In [15]:
# LGSSM P(a, z | u)
class KalmanFilter()

SyntaxError: invalid syntax (<ipython-input-15-05d5b26e194a>, line 2)

In [16]:
class z(Normal):
    def __init__(self):
        super(z, self).__init__(var=["z"])
    def forward(self):
        return {"loc": 0, "scale": 1}

In [17]:
b = z()

In [18]:
print_latex(b)

<IPython.core.display.Math object>

In [20]:
b.sample()

{'z': tensor(2.0017)}

In [ ]:
# https://github.com/simonkamronn/kvae/blob/849d631dbf2faf2c293d56a0d7a2e8564e294a51/kvae/filter.py#L82
class Kalamn_a_given_z(Normal):
    def __init__(self, z_dim, a_dim, k_dim):
        super(Kalamn_a_given_z, self).__init__(name="p_gamma", cond_var=["alpha", "z"], var=["a_pred"])
        
        self.z_dim = z_dim
        self.a_dim = a_dim
        self.k_dim = k_dim
        
        self.C = torch.tensor(np.array([0.05 * np.random.randn(self.a_dim, self.z_dim).astype(np.float32) for _ in range(self.k_dim)]))
        self.R = torch.tensor(0.03 * np.eye(self.dim_a, dtype=np.float32))
        
    def forward(self, alpha, z):
        C = torch.matmul(alpha, torch.reshape(self.C, [-1, self.a_dim, self.z_dim])) # (bs, k) x (k, dim_y*dim_z)
        C = torch.reshape(alpha, self.a_dim, self.z_dim)# (bs, dim_a, dim_z)
        
        # residual
        a_pred = torch.squeeze(tf.matmul(C, torch.squeeze(z, 2))) # (bs, dim_a)
        
        return {"a": a_pred}

    
class kalman_z_given_u_z_t_prev(Normal):
    def __init__(self, )

In [ ]:
class Kalman_a_given_z(Normal):
    def __init__(self, z_dim, u_dim, k_dim):
        super(Kalman_a_given_z, self).__init__(name="p_gamma", cond_var=["alpha", "z_prev", "u"], var=["z"])
        
        self.z_dim = z_dim
        self.u_dim = u_dim
        self.k_dim = k_dim
        
        self.A = torch.tensor(np.array([np.eye(z_dim).astype(np.float32) for _ in range(k_dim)]))
        
        self.B = torch.tensor(np.array([0.05 * np.random.randn(z_dim, u_dim).astype(np.float32) for _ in range(k_dim)]))
        
        self.Q = torch.tensor(0.08 * np.eye(z_dim, dtype=np.float32))
        
    def forward(self, alpha, z_prev, u):
        A = torch.matmul(alpha, torch.reshape(self.A, [-1, self.z_dim*self.z_dim]))  # (bs, k) x (k, dim_z*dim_z)
        A = torch.reshape(A, [-1, self.z_dim, self.z_dim])  # (bs, dim_z, dim_z)
        
        
        B = torch.matmul(alpha, torch.reshape(self.B, [-1, self.z_dim*self.u_dim]))  # (bs, k) x (k, dim_y*dim_z)
        B = torch.reshape(B, [-1, self.z_dim, self.u_dim])  # (bs, dim_y, dim_z)
        
        
        
        
        
        
        
        

In [32]:
class KalmanFilter(object):
    """
    This class defines a Kalman Filter (Linear Gaussian State Space Model), possibly with a dynamics
    parater network alpha
    """
    def __init__(self, batch_size, dim_z=4, dim_a=2, dim_u=1, dim_k=3):
        self.batch_size = batch_size
        self.dim_z = dim_z
        self.dim_a = dim_a
        self.dim_u = dim_u
        self.dim_k = dim_k
        
        self.A = torch.tensor(np.array([np.eye(self.dim_z).astype(np.float32) for _ in range(self.dim_k)]))
        
        self.B = torch.tensor(np.array([0.05 * np.random.randn(self.dim_z, self.dim_u).astype(np.float32) for _ in range(self.dim_k)]))
        
        self.C = torch.tensor(np.array([0.05 * np.random.randn(self.dim_a, self.dim_z).astype(np.float32) for _ in range(self.dim_k)]))
        
        # We use isotropic covariance matrices
        self.Q = torch.tensor(0.08 * np.eye(self.dim_z, dtype=np.float32))
        self.R = torch.tensor(0.03 * np.eye(self.dim_a, dtype=np.float32))
        
        # p(z_1)
        self.mu = torch.tensor(np.zeros((self.batch_size, self.dim_z), dtype=np.float32))
        self.Sigma = torch.tensor(np.tile(20.0 * np.eye(self.dim_z, dtype=np.float32), (self.batch_size, 1, 1)))
        
        # Initial variable a_0
        self.a_0 = torch.tensor(np.zeros((self.dim_a,), dtype=np.float32))
        
        self._alpha_sq = torch.tensor(1.)
        # process-measurement cross correlation
        self.M = 0
        
        # identity Matrix
        self._I = torch.eye(dim_z)
        

In [36]:
np.tile(20.0 * np.eye(3, dtype=np.float32), (3, 1, 1))

array([[[20.,  0.,  0.],
        [ 0., 20.,  0.],
        [ 0.,  0., 20.]],

       [[20.,  0.,  0.],
        [ 0., 20.,  0.],
        [ 0.,  0., 20.]],

       [[20.,  0.,  0.],
        [ 0., 20.,  0.],
        [ 0.,  0., 20.]]], dtype=float32)

In [35]:
torch.tensor(np.array([0.05 * np.random.randn(3, 2).astype(np.float32) for _ in range(5)])).shape

torch.Size([5, 3, 2])

In [33]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
torch.eye(3, 2)

tensor([[1., 0.],
        [0., 1.],
        [0., 0.]])

In [17]:
import numpy as np
np.zeros((3, )).shape

(3,)

In [22]:
torch.zeros((3, )).shape
torch.tensor(np.zeros((3, ))).shape

torch.Size([3])

## Define Loss function
$\mathcal{F}(\theta, \gamma, \phi)=\mathbb{E}_{q_{\phi}(\mathbf{a} | \mathbf{x})}\left[\log \frac{p_{\theta}(\mathbf{x} | \mathbf{a})}{q_{\phi}(\mathbf{a} | \mathbf{x})}+\mathbb{E}_{p_{\gamma}(\mathbf{z} | \mathbf{a}, \mathbf{u})}\left[\log \frac{p_{\gamma}(\mathbf{a} | \mathbf{z}) p_{\gamma}(\mathbf{z} | \mathbf{u})}{p_{\gamma}(\mathbf{z} | \mathbf{a}, \mathbf{u})}\right]\right]$ (euqation (6) in the paper)

$\hat{\mathcal{F}}(\theta, \gamma, \phi)=\frac{1}{I} \sum_{i} \log p_{\theta}\left(\mathbf{x} | \widetilde{\mathbf{a}}^{(i)}\right)+\log p_{\gamma}\left(\widetilde{\mathbf{a}}^{(i)}, \widetilde{\mathbf{z}}^{(i)} | \mathbf{u}\right)-\log q_{\phi}\left(\widetilde{\mathbf{a}}^{(i)} | \mathbf{x}\right)-\log p_{\gamma}\left(\widetilde{\mathbf{z}}^{(i)} | \widetilde{\mathbf{a}}^{(i)}, \mathbf{u}\right)$ (euqation (7) in the paper)